export const COUNTER_INCREMENT = "COUNTER_INCREMENT";
export const COUNTER_DECREMEMT = " COUNTER_DECREMEMT"
export const COUNTER_MULTIPLY = "COUNTER_MULTIPLY";
export const COUNTER_DIVIDE = " COUNTER_DIVIDE"